usgs_username: YOUR_USGS_USERNAME
usgs_password: YOUR_USGS_PASSWORD
dataset: landsat_ot_c2_l2
year: 2025
cloud_cover: 10
raw_landsat_dir: G:/My Drive/Raw_Landsat
temp_download_dir: temp_download
bands:
- SR_B2
- SR_B3
- SR_B4
- SR_B5
- ST_B10
- QA_PIXEL
locations:
- name: Mumbai
  latitude: 19.076
  longitude: 72.8777
  seasons:
  - name: Summer
    start_date: '2025-03-01'
    end_date: '2025-05-31'
  - name: Winter
    start_date: '2024-11-01'
    end_date: '2025-01-31'
- name: NewYorkCity
  latitude: 40.7128
  longitude: -74.006
  seasons:
  - name: Winter
    start_date: '2025-12-01'
    end_date: '2026-02-28'
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
- name: Punjab
  latitude: 30.901
  longitude: 75.8573
  seasons:
  - name: Growing
    start_date: '2025-07-01'
    end_date: '2025-09-30'
  - name: Rabi
    start_date: '2024-11-01'
    end_date: '2025-01-31'
- name: Iowa
  latitude: 41.878
  longitude: -93.0977
  seasons:
  - name: Harvest
    start_date: '2025-09-01'
    end_date: '2025-11-30'
  - name: Growing
    start_date: '2025-06-01'
    end_date: '2025-08-31'
- name: WesternGhats
  latitude: 10.1632
  longitude: 77.06
  seasons:
  - name: Summer
    start_date: '2025-03-01'
    end_date: '2025-05-31'
  - name: PostMonsoon
    start_date: '2025-10-01'
    end_date: '2025-12-31'
- name: BlackForest
  latitude: 48.05
  longitude: 8.15
  seasons:
  - name: Autumn
    start_date: '2025-09-01'
    end_date: '2025-11-30'
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
- name: Thar
  latitude: 26.9157
  longitude: 70.9083
  seasons:
  - name: Summer
    start_date: '2025-03-01'
    end_date: '2025-05-31'
  - name: Winter
    start_date: '2024-11-01'
    end_date: '2025-01-31'
- name: Atacama
  latitude: -23.8634
  longitude: -69.1328
  seasons:
  - name: Winter
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Summer
    start_date: '2024-12-01'
    end_date: '2025-02-28'
- name: Ladakh
  latitude: 34.1526
  longitude: 77.5771
  seasons:
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Spring
    start_date: '2025-04-01'
    end_date: '2025-05-31'
- name: SwissAlps
  latitude: 46.5613
  longitude: 8.3585
  cloud_cover: 20
  seasons:
  - name: Winter
    start_date: '2025-12-01'
    end_date: '2026-02-28'
  - name: Summer
    start_date: '2025-07-01'
    end_date: '2025-09-30'
- name: Chennai
  latitude: 13.0827
  longitude: 80.2707
  seasons:
  - name: Summer
    start_date: '2025-03-01'
    end_date: '2025-05-31'
  - name: NortheastMonsoon
    start_date: '2025-10-01'
    end_date: '2025-12-31'
- name: Sydney
  latitude: -33.8688
  longitude: 151.2093
  seasons:
  - name: Winter
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Summer
    start_date: '2024-12-01'
    end_date: '2025-02-28'
- name: Sundarbans
  latitude: 21.9497
  longitude: 89.1833
  seasons:
  - name: Summer
    start_date: '2025-03-01'
    end_date: '2025-05-31'
  - name: Winter
    start_date: '2024-11-01'
    end_date: '2025-01-31'
- name: Everglades
  latitude: 25.2866
  longitude: -80.8987
  seasons:
  - name: Winter
    start_date: '2025-12-01'
    end_date: '2026-02-28'
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
- name: Sahara
  latitude: 29.9792
  longitude: 31.1342
  seasons:
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Winter
    start_date: '2024-12-01'
    end_date: '2025-02-28'
- name: Tokyo
  latitude: 35.6762
  longitude: 139.6503
  seasons:
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Winter
    start_date: '2024-12-01'
    end_date: '2025-02-28'
- name: Amazon
  latitude: -3.1190
  longitude: -60.0217
  cloud_cover: 25
  seasons:
  - name: DrySeason
    start_date: '2025-07-01'
    end_date: '2025-09-30'
  - name: WetSeason
    start_date: '2025-01-01'
    end_date: '2025-03-31'
- name: Serengeti
  latitude: -2.3333
  longitude: 34.8333
  seasons:
  - name: DrySeason
    start_date: '2025-06-01'
    end_date: '2025-09-30'
  - name: GreenSeason
    start_date: '2024-11-01'
    end_date: '2025-01-31'
- name: Yakutsk
  latitude: 62.0355
  longitude: 129.6755
  seasons:
  - name: Summer
    start_date: '2025-06-01'
    end_date: '2025-08-31'
  - name: Spring
    start_date: '2025-04-01'
    end_date: '2025-05-31'
- name: Patagonia
  latitude: -50.9423
  longitude: -73.4068
  cloud_cover: 25
  seasons:
  - name: Summer
    start_date: '2024-12-01'
    end_date: '2025-02-28'
  - name: Autumn
    start_date: '2025-03-01'
    end_date: '2025-05-31'

